name: diagonal_scrollview_example
description: Demonstrates how to use the diagonal_scrollview plugin.
author: Ranfi Castillo de Aza <rj_castillo@outlook.com>

dependencies:
  flutter:
    sdk: flutter
