name: diagonal_scrollview
description: A Flutter package project to enable the scrolling over both, the vertical and horizontal axis at the same time, as well as zooming.
version: 0.1.0
homepage: https://github.com/RanfiCD/diagonal_scrollview

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

